### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by siberianhigh** [andremrsantos/htspop#1]
Hi Andre,

I've tried to install htspop, but got the following error:

> Error : (converted from warning) /tmp/RtmpQ0vzDu/Rbuild2df7e52ceb314/htspop/man/htspop-package.Rd:26: All text must be in a section
> ERROR: installing Rd objects failed for package ‘htspop’
> removing ‘/usr/local/lib/R/site-library/htspop’
> Error: Failed to install 'htspop' from GitHub:
>   (converted from warning) installation of package ‘/tmp/RtmprFul5X/file2d8e76d0e73d7/htspop_0.1.0.tar.gz’ had non-zero exit status

R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)

**Comment by andremrsantos** [comment]
Hi @siberianhigh ,
I made a commit that I think it fixes the bug and allows to install it.

Tell me if it was fixed.

However, this codebase hasn't been released and few tests were implemented. Thus, I recommend caution on using it. I hope to get some time to make a more complete version soon.

**Comment by siberianhigh** [comment]
It works now, thanks!
I'm most interested in your implementation of Reich Fst.

**Comment by andremrsantos** [comment]
Okay, I hope it helps
